---
abstract: 'Support for RFC3501 Internet Message Access Protocol (IMAP4)'
author:
  - 'Tom Molesworth <protocol-imap@entitymodel.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::CheckDeps: 0.010
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Protocol-IMAP
requires:
  Authen::SASL: 0
  Encode::IMAPUTF7: 0
  POSIX: 0
  Socket: 0
  Time::HiRes: 0
  parent: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Protocol-IMAP
  homepage: http://search.cpan.org/dist/Protocol-IMAP/
version: 0.004
